name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup_rmq:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: mer-team/rabbitmq-mng-action@v1.2
      with:
        RABBITMQ_USER: 'username'
        RABBITMQ_PASS: 'password'
        RABBITMQ_PORT: 5672
        RABBITMQ_MNG_PORT: 15672
        RABBITMQ_TAG: '3-management-alpine'
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Generate NuGet package
      run: 
        dotnet pack -o NugetPackages
    - name: Push generated package to GitHub registry
      run:
        dotnet nuget push "**/*.nupkg" -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
